apiVersion: v1
kind: Pod
metadata:
  labels:
    app: slow-calc
  name: slow-calc
spec:
  restartPolicy: Never
  containers:
  - image: attensidev/slowcalc:v2
    name: slow-calc
    resources: {}
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
