apiVersion: v1
kind: Service
metadata:
  labels:
    service: slow-calc-svc
  name: slow-calc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: slow-calc
  type: LoadBalancer
